### ISSUE TITLE
[WISE Bug]: ClassNotFoundException when trying to start the builder

### ISSUE THREAD

**Issue by algodbout** [WISE-Developers/Project_issues#177]
### What happened?

When starting the builder with the command `java -jar ./WISE_Builder.jar -j ./jobs`, the exception below appears. This happens on 
 - Ubuntu 20.04 
 - Ubuntu 22.04 
 - Java 8 
 - OpenJDK 17

### Version

(Ubuntu 2022) v1.0.0-beta

### What component are you seeing the problem on?

Builder

### Relevant log output

```shell
Exception in thread "main" java.lang.NoClassDefFoundError: ca/wise/fgm/output/IOutputOptions
    at ca.wise.main.Main.main(Main.java:339)
Caused by: java.lang.ClassNotFoundException: ca.wise.fgm.output.IOutputOptions
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
    ... 1 more
```

### Approvals Process

- [ ] Testing For Issue
- [ ] Executive Approval
- [ ] Merge

**Comment by spydmobile** [comment]
I can confirm this with my own tests.
```
root@e8e1c0e57204:/usr/src/app# /usr/bin/java -jar /usr/bin/WISE_Builder.jar -j /root/app_data/wisedemo_jobs   
Exception in thread "main" java.lang.NoClassDefFoundError: ca/wise/fgm/output/IOutputOptions
        at ca.wise.main.Main.main(Main.java:339)
Caused by: java.lang.ClassNotFoundException: ca.wise.fgm.output.IOutputOptions
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 1 more
root@e8e1c0e57204:/usr/src/app# which java
/usr/bin/java
root@e8e1c0e57204:/usr/src/app# 
```

**Comment by algodbout** [comment]
I confirm WISE-Developers/WISE_Builder_Component#2 fixed the issue. The builder does not output a `ClassNotFoundException` anymore and can be started properly.

**Comment by spydmobile** [comment]
Thanks @algodbout - closing this.
